-- =======================================================
-- SQL SETUP UNTUK SUPABASE (OUR LOVE VAULT & MEMORIES)
-- Salin dan jalankan (Run) kode SQL ini di Supabase SQL Editor
-- =======================================================

-- 1. Buat Tabel 'memories' (Untuk Foto, Video & Catatan Kenangan)
CREATE TABLE IF NOT EXISTS public.memories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date DATE NOT NULL,
  category TEXT DEFAULT 'favorite',
  note TEXT,
  type TEXT DEFAULT 'photo',
  media_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Buat Tabel 'settings' (Untuk Profil Pasangan & Tanggal Spesial)
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value JSONB,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Aktifkan Row Level Security (RLS) & Berikan Izin Akses Publik
ALTER TABLE public.memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Kebijakan Akses Penuh untuk Tabel
DROP POLICY IF EXISTS "Public Full Access Memories" ON public.memories;
CREATE POLICY "Public Full Access Memories" ON public.memories
  FOR ALL
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Public Full Access Settings" ON public.settings;
CREATE POLICY "Public Full Access Settings" ON public.settings
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- 4. Buat Storage Bucket 'memories' (Public) untuk Menyimpan File Foto & Video
INSERT INTO storage.buckets (id, name, public)
VALUES ('memories', 'memories', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Kebijakan Akses Storage Bucket 'memories'
DROP POLICY IF EXISTS "Public Storage Upload Access" ON storage.objects;
CREATE POLICY "Public Storage Upload Access" ON storage.objects
  FOR ALL
  USING (bucket_id = 'memories')
  WITH CHECK (bucket_id = 'memories');
